# NAO ESTOU USANDO MAIS

version: '3.7'
services:
  prisma:
    container_name: uncle-prisma
    image: prismagraphql/prisma:$PRISMA_VERSION
    restart: always
    ports:
      - '$PRISMA_SERVER_PORT:$PRISMA_SERVER_PORT'
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
        port: $PRISMA_SERVER_PORT
        databases:
          default:
            connector: $DATABASE_CONNECTOR
            host: $DATABASE_HOST
            port: $DATABASE_PORT
            user: $DATABASE_USER
            password: $DATABASE_PASSWORD
            database: $DATABASE_NAME
            # connectionLimit: PRISMA_CONNECTION_LIMIT
            migrations: true # It's enable for default
  postgres:
    image: postgres:$POSTGRES_VERSION
    container_name: uncle-db
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - /var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: uncle-pgadmin
    depends_on:
      - postgres
    ports:
      - '80:80'
    volumes:
      - /var/lib/pgadmin
      - /pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
